// PicoTTL - TTL video framework for the Raspberry Pi Pico 2 (RP2350)
//
// fonts/IbmCga8x8.hpp
// Original IBM CGA 8x8 character set (code page 437).
//
// PUBLIC API (opt-in resource) - include explicitly; it is not part of
// the PicoTTL.hpp umbrella so that applications not using text pay no
// flash cost. Built-in fonts are named by provenance and cell size
// (kIbmMda9x14, kIbmCga8x8, future kIbmVga8x16, ...) so vendor and
// user fonts can coexist unambiguously in this namespace.
//
// Copyright (c) 2026 Jesús Fernández Gamito
// SPDX-License-Identifier: MIT

#pragma once

#include "picottl/Font.hpp"

namespace picottl::fonts {

/// The original IBM CGA 8x8 character set (256 glyphs, code page 437).
///
/// One byte per glyph row, MSB-first. On the 640x200 raster this gives
/// the classic 80x25 text grid; on 320x200, 40x25 - both exact, with
/// no partial cells.
///
/// underlineRow is 7: real CGA text has no underline attribute, but
/// PicoTTL keeps the underline attribute and the underline cursor
/// functional on every backend (standards are defaults, not limits),
/// drawing the line on the cell's bottom row - where the CGA hardware
/// cursor lived.
///
/// Flash cost: 256 glyphs x 8 rows x 1 byte = 2048 bytes (linked only
/// when referenced). Generated by tools/generate_cga_font.py from an
/// 8x8 IBM character ROM dump - do not edit the data by hand.
extern const Font kIbmCga8x8;

} // namespace picottl::fonts
