// PicoTTL - TTL video framework for the Raspberry Pi Pico 2 (RP2350)
//
// fonts/IbmEga8x14.hpp
// Original IBM EGA 8x14 character set (code page 437).
//
// PUBLIC API (opt-in resource) - include explicitly; it is not part of
// the PicoTTL.hpp umbrella so that applications not using text pay no
// flash cost. Built-in fonts are named by provenance and cell size
// (kIbmMda9x14, kIbmCga8x8, kIbmEga8x14, ...) so vendor and user fonts
// can coexist unambiguously in this namespace.
//
// Copyright (c) 2026 Jesús Fernández Gamito
// SPDX-License-Identifier: MIT

#pragma once

#include "picottl/Font.hpp"

namespace picottl::fonts {

/// The original IBM EGA 8x14 character set (256 glyphs, code page 437).
///
/// One byte per glyph row, MSB-first. On the 640x350 raster this gives
/// the classic 80x25 text grid - exact, with no partial cells; using
/// the 8x8 CGA font on the same raster gives the EGA's 80x43 "small
/// text" mode.
///
/// PROVENANCE (verified 2026-07-14): generated from an authentic IBM
/// EGA character ROM dump, byte-compared identical to the IBM VGA 8x14
/// ROM font (0/256 glyphs differ). Note that this project's MDA font
/// (kIbmMda9x14) derives from this same EGA dump under the widely
/// documented glyph-identity claim; identity with a genuine MDA card
/// ROM (IBM 5788005) has not been independently verified.
///
/// underlineRow is 12, matching the MDA convention for this 14-line
/// glyph set: real EGA color text had no underline attribute, but
/// PicoTTL keeps underline (and the underline cursor) functional on
/// every backend (standards are defaults, not limits).
///
/// Flash cost: 256 glyphs x 14 rows x 1 byte = 3584 bytes (linked only
/// when referenced). Generated by tools/generate_ega_font.py - do not
/// edit the data by hand.
extern const Font kIbmEga8x14;

} // namespace picottl::fonts
