// PicoTTL - TTL video framework for the Raspberry Pi Pico 2 (RP2350)
//
// fonts/IbmEga8x14Cp850.hpp
// IBM EGA 8x14 character set, code page 850 (DOS Multilingual/Latin-1).
//
// PUBLIC API (opt-in resource) - include explicitly; it is not part of
// the PicoTTL.hpp umbrella so that applications not using it pay no
// flash cost.
//
// Copyright (c) 2026 Jesús Fernández Gamito
// SPDX-License-Identifier: MIT

#pragma once

#include "picottl/Font.hpp"

namespace picottl::fonts {

/// IBM EGA 8x14 character set for code page 850 (256 glyphs).
///
/// A complete, independent dataset in CP850 byte order - the original
/// IBM model: DOS's MODE CON CP SELECT loaded whole fonts from
/// EGA.CPI, never a base font with supplements. Compared with CP437,
/// CP850 keeps ~200 characters at identical positions, relocates 4
/// (cent, yen, pilcrow, section) and replaces 43 - mostly mixed
/// double/single box-drawing and Greek/math symbols - with the
/// uppercase accented letters CP437 lacked plus copyright, registered,
/// multiplication and typographic signs. The full position-by-position
/// inventory is documented in docs/architecture.md.
///
/// One byte per glyph row, MSB-first. underlineRow = 12, matching the
/// CP437 dataset (see kIbmEga8x14 for the rationale).
///
/// Flash cost: 3584 bytes (linked only when referenced). Generated by
/// tools/generate_ega_font.py - do not edit the data by hand.
///
/// PROVENANCE NOTE: the source dump is the CP850 8x14 font from IBM
/// PC-DOS 2000's codepage file (EGA.CPI lineage). CPI letterforms
/// differ subtly from the EGA/VGA ROM even in the ASCII range; this is
/// authentic - selecting CP850 on real DOS replaced ALL 256 glyphs,
/// and users saw exactly this rendition.
extern const Font kIbmEga8x14Cp850;

} // namespace picottl::fonts
