// PicoTTL - TTL video framework for the Raspberry Pi Pico 2 (RP2350)
//
// fonts/IbmMda9x14Cp850.hpp
// IBM MDA 9x14 character set, code page 850 (DOS Multilingual/Latin-1).
//
// PUBLIC API (opt-in resource) - include explicitly; it is not part of
// the PicoTTL.hpp umbrella so that applications not using it pay no
// flash cost.
//
// Copyright (c) 2026 Jesús Fernández Gamito
// SPDX-License-Identifier: MIT

#pragma once

#include "picottl/Font.hpp"

namespace picottl::fonts {

/// IBM MDA 9x14 character set for code page 850 (256 glyphs).
///
/// A complete, independent dataset in CP850 byte order - the original
/// IBM model: DOS's MODE CON CP SELECT loaded whole fonts from
/// EGA.CPI, never a base font with supplements. Compared with CP437,
/// CP850 keeps ~200 characters at identical positions (ASCII range
/// letterforms follow the CPI design, see PROVENANCE), relocates 4
/// (cent, yen, pilcrow, section) and replaces 43 - mostly mixed
/// double/single box-drawing and Greek/math symbols - with the
/// uppercase accented letters CP437 lacked (A/E/I/O/U with all
/// accents, eth, thorn, o-slash...) plus copyright, registered,
/// multiplication and typographic signs. The full position-by-position
/// inventory is documented in docs/architecture.md.
///
/// Glyphs are pre-expanded to the full 9-dot cell (2 bytes per row).
/// The MDA 9th-column rule applies by code POSITION (0xC0..0xDF), as
/// in the hardware circuit; IBM drew the CP850 letters that live in
/// that range (a-tilde, eth, E/I with accents...) with pixel column 8
/// clear precisely so they survive the replication - verified on this
/// dataset (only 0xD5, dotless i, touches column 8).
///
/// Flash cost: 7168 bytes (linked only when referenced). Generated by
/// tools/generate_mda_font.py - do not edit the data by hand.
///
/// PROVENANCE NOTE: the source dump is the CP850 8x14 font from IBM
/// PC-DOS 2000's codepage file (EGA.CPI lineage). CPI letterforms
/// differ subtly from the EGA/VGA ROM even in the ASCII range; this is
/// authentic - selecting CP850 on real DOS replaced ALL 256 glyphs,
/// and users saw exactly this rendition.
extern const Font kIbmMda9x14Cp850;

} // namespace picottl::fonts
