// PicoTTL - TTL video framework for the Raspberry Pi Pico 2 (RP2350)
//
// fonts/IbmMda9x14.hpp
// Original IBM MDA 9x14 character set (code page 437).
//
// PUBLIC API (opt-in resource) - include explicitly; it is not part of
// the PicoTTL.hpp umbrella so that applications not using text pay no
// flash cost. Built-in fonts are named by provenance and cell size
// (kIbmMda9x14, future kIbmCga8x8, kIbmVga8x16, ...) so vendors and
// user fonts can coexist unambiguously in this namespace.
//
// Copyright (c) 2026 Jesús Fernández Gamito
// SPDX-License-Identifier: MIT

#pragma once

#include "picottl/Font.hpp"

namespace picottl::fonts {

/// The original IBM MDA 9x14 character set (256 glyphs, code page 437).
///
/// Glyphs are pre-expanded to the full 9-dot cell (2 bytes per row):
/// the MDA hardware rule - codes 0xC0..0xDF replicate pixel column 8
/// into column 9 for box-drawing continuity, everything else gets a
/// blank 9th column - is baked into the data, keeping the renderer
/// completely generic.
///
/// Flash cost: 256 glyphs x 14 rows x 2 bytes = 7168 bytes (linked only
/// when referenced). Generated by tools/generate_mda_font.py from an
/// 8x14 IBM character ROM dump - do not edit the data by hand.
///
/// PROVENANCE NOTE: the source dump is an IBM EGA character ROM
/// (verified byte-identical to the IBM VGA 8x14 ROM font), used here
/// under the widely documented claim that IBM shared the 14-line
/// glyph set across MDA, EGA and VGA. Identity with a genuine MDA
/// card ROM (IBM 5788005) has not been independently verified.
extern const Font kIbmMda9x14;

} // namespace picottl::fonts
